---
author: "Sarthak"
date: "April 10, 2019"
output: pdf_document
---
<!-- load the data -->
```{r}
library(readxl)
library(lme4)
library(lmerTest)
library(car)
library(MuMIn)
library(afex)
```

```{r}
data <- read_excel("../Data/PredictingOutcomes_ParticipantPredictions.xlsx", sheet = "Study 1B")

# divide the data based on the generator
data1 <- data[data$generator == "analyst",]
data2 <- data[data$generator == "bingo",]
data3 <- data[data$generator == "stock",]
```


calculate the proportion of participants who predicted the prediction_recode=1 for each terminal_streak_length from 1 to 7

```{r}
prop1 <- aggregate(data1$prediction_recode, by = list(data1$terminal_streak_length), FUN = mean)
prop2 <- aggregate(data2$prediction_recode, by = list(data2$terminal_streak_length), FUN = mean)
prop3 <- aggregate(data3$prediction_recode, by = list(data3$terminal_streak_length), FUN = mean)
```

```{r}
plot(prop1$Group.1,prop1$x, type = "l",ylim=c(0.0,0.9), xlab = "Terminal Streak", ylab = "Proportion of Prediction Recode=1", main = "Proportion of Prediction Recode=1 for each Terminal Streak")
lines(prop2$Group.1,prop2$x, col = "red")
lines(prop3$Group.1,prop3$x,  col = "blue")
abline(h = 0.5, col = "green")
legend("topright", legend = c("Analyst", "Bingo", "Stock"), col = c("black", "red", "blue"), lty = 1:3)
```

```{r}
aov1<-aov_ez('participant_id','prediction_recode',data, between=c('generator'),within=c('terminal_streak_length'))
aov1

pairwise.t.test(data$prediction_recode, data$generator, p.adjust.method = "bonferroni")
```
```{r}
id <- unique(data1$participant_id)

slope <- c()

for (i in id){
x <- as.character(i)
datax <- data1[data1$participant_id == x,]
# datax <- datax[datax$terminal_streak_length != "1",]
model <- glm(prediction_recode ~ terminal_streak_length, data = datax)
beta <- coef(model)[2]
odds <- exp(beta)
slope <- c(slope, beta)
}

slope <- slope*500
hist(slope,breaks=30,xlim=c(-200,200),prob=TRUE,main="AnalystUnknown")
curve(dnorm(x, mean = mean(slope), sd = sd(slope)), add = TRUE, col = "black")
```
logistic regression
```{r}
id <- unique(data2$participant_id)

slope <- c()

for (i in id){
x <- as.character(i)
datax <- data2[data2$participant_id == x,]
model <- glm(prediction_recode ~ terminal_streak_length, data = datax)
slope <- c(slope, coef(model)[2])
}
slope <- slope*500

hist(slope,breaks=30,xlim=c(-200,200),prob=TRUE,main="BingoUnknown")
curve(dnorm(x, mean = mean(slope), sd = sd(slope)), add = TRUE, col = "black")
```
```{r}
id <- unique(data3$participant_id)

slope <- c()

for (i in id){
x <- as.character(i)
datax <- data3[data3$participant_id == x,]
model <- glm(prediction_recode ~ terminal_streak_length, data = datax)
slope <- c(slope, coef(model)[2])
}
slope <- slope*500

hist(slope,breaks=30,xlim=c(-200,200),prob=TRUE,main="StockUnknown")
curve(dnorm(x, mean = mean(slope), sd = sd(slope)), add = TRUE, col = "black")
```

```{r}
data_dem<- read_excel("../Data/PredictingOutcomes_ParticipantDemographics.xlsx", sheet = "Study 2B")

# print(data)
```

create a map like data structure to store the unique participant id with there corresponding gender
```{r}
map <- data.frame(unique(data_dem$participant_id), data_dem$gender)
colnames(map) <- c("participant_id","gender")
# map
```

```{r}
dataf <- data[,c(2,3,8,10)]
# print(data1)
```

```{r}

df <- merge(dataf, map, by = "participant_id")
df_total <- df[df$gender=='0' | df$gender=='1',]
# male <- df[df$gender=='0',]
# female <- df[df$gender=='1',]
# chisq.test(male$prediction_recode, female$prediction_recode,correct=FALSE)
check <- table(df_total$gender, df_total$terminal_streak_length)
print(check)
test <- table(df_total$gender, df_total$prediction_recode)
print(test)
chisq.test(test)
```

```{r}
df <- df_total[df_total$generator=='analyst',]
test <- table(df$gender, df$prediction_recode)
print(test)
chisq.test(test)
```

```{r}
df <- df_total[df_total$generator=='bingo',]
test <- table(df$gender, df$prediction_recode)
print(test)
chisq.test(test)
```

```{r}
df <- df_total[df_total$generator=='stock',]
test <- table(df$gender, df$prediction_recode)
print(test)
chisq.test(test)
```

