---
author: "Sarthak"
date: "April 10, 2019"
output: pdf_document
---
<!-- load the data -->
```{r}
library(readxl)
library(lme4)
library(lmerTest)
library(car)
library(MuMIn)
```

```{r}
data <- read_excel("../Data/PredictingOutcomes_ParticipantPredictions.xlsx", sheet = "Study 1A")

# divide the data based on the generator
data1 <- data[data$generator == "analyst",]
data2 <- data[data$generator == "bingo",]
data3 <- data[data$generator == "stock",]
```


calculate the mean of prediciotn_recode for each terminwal streak from 1 to 7

```{r}
mean1 <- aggregate(data1$prediction_recode, by = list(data1$terminal_streak_length), FUN = mean)
mean2 <- aggregate(data2$prediction_recode, by = list(data2$terminal_streak_length), FUN = mean)
mean3 <- aggregate(data3$prediction_recode, by = list(data3$terminal_streak_length), FUN = mean)
```




```{r}
plot(mean1$Group.1,mean1$x, type = "l",ylim=c(0,100), xlab = "Terminal Streak", ylab = "Mean of Prediction Recode", main = "Mean of Prediction Recode for each Terminal Streak")
lines(mean2$Group.1,mean2$x, col = "red")
lines(mean3$Group.1,mean3$x,  col = "blue")
abline(h = 50, col = "green")
legend("topright", legend = c("Analyst", "Bingo", "Stock"), col = c("black", "red", "blue"), lty = 1:3)
```

calculate the mean of prediciotn_recode for each participant_id

```{r}
mean1_id <- aggregate(data1$prediction_recode, by = list(data1$participant_id), FUN = mean)
mean2_id <- aggregate(data2$prediction_recode, by = list(data2$participant_id), FUN = mean)
mean3_id <- aggregate(data3$prediction_recode, by = list(data3$participant_id), FUN = mean)

```
apply anova on mean1_id, mean2_id, mean3_id collecively in the same model 

